### ISSUE TITLE
[FS Overview] "MORE..." link inaccessible in some screen sizes

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oekg#23]
## Description of the issue

After filling out a Fact Sheet with two windows side by side, I wanted to browse existing Factsheets. However, I was unable to click on them. The "MORE..." link was inaccessible to me, because the shrunk down container pushed the link out of the visible area. There was no option to scroll to the link

## Ideas of solution

1 Make the entire container clickable OR 
2 enable scrolling within the container OR 
3 create a button that is always shown, even in a shrunk down container.

![no_more](https://user-images.githubusercontent.com/42000429/229817986-4dc9c8bc-59d5-4a03-976e-11bb2983b942.png)

**Comment by stap-m** [comment]
I guess this should be looked at when the design is final.

**Comment by adelmemariani** [comment]
I entirely changed the overview page. I tried to adapt it to the OEP logo. Therefore I used hexagons and removed the 'more button', and made the hexagons clickable [ instead of clicking 'More', we can click anywhere of the corresponding hexagon ] :

![Screenshot 2023-04-20 at 21 41 50](https://user-images.githubusercontent.com/7637364/234301202-f2ec9d13-c46c-4660-a685-bf51114b733e.png)

**Comment by adelmemariani** [comment]
As we discussed in the 7th SIROP project meeting, the main page should have a table that contains all factsheets. Therefore I changed the main page:

![Screenshot 2023-04-28 at 15 35 19](https://user-images.githubusercontent.com/7637364/235162778-80bcf18c-3c20-4ae8-b8a5-66c4c02a6a38.png)

If it is fine, then we can close this issue.

**Comment by stap-m** [comment]
Looks good, thanks!
